#ifndef GLOB_MACROS_H
#define GLOB_MACROS_H

#define POSITIVE 1
#define NEGATIVE -1
#define PLAYER_RADIUS 50
#define BULLET_SPEED 30
#define ENEMY_TYPE_ONE_SIZE 40
#define BULLET_TYPE_ONE_SIZE 30

#endif 
